Update CI.yml

diff --git a/.github/workflows/CI.yml b/.github/workflows/CI.yml
--- a/.github/workflows/CI.yml
+++ b/.github/workflows/CI.yml
@@ -43,12 +43,6 @@ jobs:
         run: npx eslint . --config ./.github/workflows/.eslintrc.js --format=json --output-file=$ESLINT_REPORT_PATH
         continue-on-error: true
 
-      - name: Check ESLint Exit Code
-        id: eslint-exit-code
-        run: |
-          echo ::set-output name=eslint_exit_code::${{ steps.eslint-step.outcome }}
-          echo 'value: ' ${{ steps.eslint-exit-code.outputs.eslint_exit_code }}
-
       - name: Show ESLint Report
         run: cat $ESLINT_REPORT_PATH
 
@@ -56,8 +50,11 @@ jobs:
         run: |
           eslint_exit_code=${{ steps.eslint-exit-code.outputs.eslint_exit_code }}
           if [ $eslint_exit_code -ne 0 ]; then
-            echo "ESLint found issues. Exiting with code $eslint_exit_code."
-            exit $eslint_exit_code
+            echo "ESLint found issues with a code of $eslint_exit_code."
+            echo "Exiting the workflow with an error status."
+            exit 1
+          else
+            echo "ESLint found no issues. Continuing with the workflow."
           fi
 
       #- name: Check Code Quality
